/*!
  _   _  ___  ____  ___ ________  _   _   _   _ ___   
 | | | |/ _ \|  _ \|_ _|__  / _ \| \ | | | | | |_ _| 
 | |_| | | | | |_) || |  / / | | |  \| | | | | || | 
 |  _  | |_| |  _ < | | / /| |_| | |\  | | |_| || |
 |_| |_|\___/|_| \_\___/____\___/|_| \_|  \___/|___|
                                                                                                                                                                                                                                                                                                                                       
=========================================================
* Horizon UI - v1.1.0
=========================================================

* Product Page: https://www.horizon-ui.com/
* Copyright 2022 Horizon UI (https://www.horizon-ui.com/)

* Designed and Coded by Simmmple

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/

// Chakra imports
import React from "react";

import tableDataComplexPrediction from "views/admin/default/variables/tableDataComplex.json";

import ComplexTable from "views/admin/default/components/ComplexTable";

// Chakra imports
import {

  Box,
  FormControl,
  FormLabel,
  Button,
 
  Container,

  SliderMark,
  Slider,
  SliderTrack,
  SliderFilledTrack,
  SliderThumb,
  Text,
  Flex
} from "@chakra-ui/react";
import { columnsDataComplexPrediction } from "views/admin/default/variables/columnsData";
import { ThemeEditorAccordionItem } from "@hypertheme-editor/chakra-ui";
import { CgSleep } from "react-icons/cg";


// Custom components

export default function Overview() {
  const format = (val) => `$` + val;

  const estData = [
    {
        "": 0,
        "name": "M3X Media",
        "market": "Games",
        "status": "closed",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 688842,
        "dats": 1,
        "__1": ""
    },
    {
        "": 2,
        "name": "Leti Arts",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 124160,
        "dats": 1,
        "__1": ""
    },
    {
        "": 3,
        "name": "Monumental Games",
        "market": "Games",
        "status": "closed",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 710977,
        "dats": 1,
        "__1": ""
    },
    {
        "": 4,
        "name": "Movinto Fun",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 939081,
        "dats": 1,
        "__1": ""
    },
    {
        "": 5,
        "name": "Nix Hydra",
        "market": "Mobile Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 975999,
        "dats": 1,
        "__1": ""
    },
    {
        "": 6,
        "name": "Kool Kid Kent",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 203559,
        "dats": 1,
        "__1": ""
    },
    {
        "": 8,
        "name": "Kamcord",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 332575,
        "dats": 1,
        "__1": ""
    },
    {
        "": 10,
        "name": "Just Sing It",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 750306,
        "dats": 1,
        "__1": ""
    },
    {
        "": 11,
        "name": "Kogeto",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 695858,
        "dats": 1,
        "__1": ""
    },
    {
        "": 12,
        "name": "MogiMe",
        "market": "Mobile Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 428487,
        "dats": 1,
        "__1": ""
    },
    {
        "": 13,
        "name": "Junko Tada",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 397777,
        "dats": 1,
        "__1": ""
    },
    {
        "": 14,
        "name": "Kybernesis",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 212508,
        "dats": 1,
        "__1": ""
    },
    {
        "": 15,
        "name": "OUYA",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 590016,
        "dats": 1,
        "__1": ""
    },
    {
        "": 16,
        "name": "Minefold",
        "market": "Games",
        "status": "closed",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 817835,
        "dats": 1,
        "__1": ""
    },
    {
        "": 17,
        "name": "Nanali",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 30471,
        "dats": 1,
        "__1": ""
    },
    {
        "": 18,
        "name": "Lolapps",
        "market": "Games",
        "status": "acquired",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 951938,
        "dats": 1,
        "__1": ""
    },
    {
        "": 19,
        "name": "Mind Candy",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 909354,
        "dats": 1,
        "__1": ""
    },
    {
        "": 20,
        "name": "Mandalay Sports Media (MSM)",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 591202,
        "dats": 1,
        "__1": ""
    },
    {
        "": 21,
        "name": "Kiro'o Games",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 63196,
        "dats": 1,
        "__1": ""
    },
    {
        "": 22,
        "name": "Lingorami",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 130752,
        "dats": 1,
        "__1": ""
    },
    {
        "": 24,
        "name": "Pathfire",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 61222,
        "dats": 1,
        "__1": ""
    },
    {
        "": 25,
        "name": "Last 2 Left",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 407779,
        "dats": 1,
        "__1": ""
    },
    {
        "": 26,
        "name": "MIG China",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 594407,
        "dats": 1,
        "__1": ""
    },
    {
        "": 27,
        "name": "Netgamix Inc",
        "market": "Games",
        "status": "closed",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 30454,
        "dats": 1,
        "__1": ""
    },
    {
        "": 28,
        "name": "Lunagames",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 229965,
        "dats": 1,
        "__1": ""
    },
    {
        "": 29,
        "name": "Meez",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 476340,
        "dats": 1,
        "__1": ""
    },
    {
        "": 31,
        "name": "Inzen Studio",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 170105,
        "dats": 1,
        "__1": ""
    },
    {
        "": 32,
        "name": "Mybandstock",
        "market": "Games",
        "status": "closed",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 949262,
        "dats": 1,
        "__1": ""
    },
    {
        "": 33,
        "name": "OneWed (Formerly Nearlyweds)",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 238923,
        "dats": 1,
        "__1": ""
    },
    {
        "": 34,
        "name": "Mindshapes",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 196601,
        "dats": 1,
        "__1": ""
    },
    {
        "": 35,
        "name": "LOVEFiLM",
        "market": "Games",
        "status": "acquired",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 349954,
        "dats": 1,
        "__1": ""
    },
    {
        "": 36,
        "name": "KidzVuz",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 459982,
        "dats": 1,
        "__1": ""
    },
    {
        "": 38,
        "name": "MadRat Games",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 600314,
        "dats": 1,
        "__1": ""
    },
    {
        "": 39,
        "name": "MoviePass",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 706665,
        "dats": 1,
        "__1": ""
    },
    {
        "": 41,
        "name": "Kermdinger Studios",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 482031,
        "dats": 1,
        "__1": ""
    },
    {
        "": 42,
        "name": "Octapoly",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 276041,
        "dats": 1,
        "__1": ""
    },
    {
        "": 43,
        "name": "LeftRight Studios",
        "market": "Mobile Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 226751,
        "dats": 1,
        "__1": ""
    },
    {
        "": 44,
        "name": "iStreamPlanet",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 456925,
        "dats": 1,
        "__1": ""
    },
    {
        "": 45,
        "name": "Music Cave Studios",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 822519,
        "dats": 1,
        "__1": ""
    },
    {
        "": 46,
        "name": "Nuday Games",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 535257,
        "dats": 1,
        "__1": ""
    },
    {
        "": 47,
        "name": "Peak Games",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 164759,
        "dats": 1,
        "__1": ""
    },
    {
        "": 48,
        "name": "MetroGames",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 506066,
        "dats": 1,
        "__1": ""
    },
    {
        "": 49,
        "name": "LuckyLabs",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 977138,
        "dats": 1,
        "__1": ""
    },
    {
        "": 50,
        "name": "Knowledge Adventure",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 300341,
        "dats": 1,
        "__1": ""
    },
    {
        "": 51,
        "name": "Kizziang",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 595811,
        "dats": 1,
        "__1": ""
    },
    {
        "": 52,
        "name": "OONi",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 995463,
        "dats": 1,
        "__1": ""
    },
    {
        "": 53,
        "name": "Moblyng",
        "market": "Games",
        "status": "closed",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 134182,
        "dats": 1,
        "__1": ""
    },
    {
        "": 55,
        "name": "Lagoa",
        "market": "Games",
        "status": "acquired",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 516543,
        "dats": 1,
        "__1": ""
    },
    {
        "": 56,
        "name": "Kingdom Scene Endeavors",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 124638,
        "dats": 1,
        "__1": ""
    },
    {
        "": 59,
        "name": "Midnight Studios",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 805964,
        "dats": 1,
        "__1": ""
    },
    {
        "": 60,
        "name": "Motionbox",
        "market": "Games",
        "status": "acquired",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 163011,
        "dats": 1,
        "__1": ""
    },
    {
        "": 61,
        "name": "MyGoGames",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 403581,
        "dats": 1,
        "__1": ""
    },
    {
        "": 62,
        "name": "Linden Lab",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 243315,
        "dats": 1,
        "__1": ""
    },
    {
        "": 63,
        "name": "Open Wager",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 889840,
        "dats": 1,
        "__1": ""
    },
    {
        "": 64,
        "name": "Kingnet",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 100495,
        "dats": 1,
        "__1": ""
    },
    {
        "": 65,
        "name": "mmCHANNEL",
        "market": "Games",
        "status": "closed",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 821066,
        "dats": 1,
        "__1": ""
    },
    {
        "": 66,
        "name": "KUBOO",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 570025,
        "dats": 1,
        "__1": ""
    },
    {
        "": 67,
        "name": "KlickSports",
        "market": "Mobile Games",
        "status": "closed",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 963489,
        "dats": 1,
        "__1": ""
    },
    {
        "": 68,
        "name": "PAYMILL",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 544695,
        "dats": 1,
        "__1": ""
    },
    {
        "": 69,
        "name": "Lumexis",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 595913,
        "dats": 1,
        "__1": ""
    },
    {
        "": 70,
        "name": "Nonoba",
        "market": "Games",
        "status": "closed",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 470528,
        "dats": 1,
        "__1": ""
    },
    {
        "": 71,
        "name": "Kidamom",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 71865,
        "dats": 1,
        "__1": ""
    },
    {
        "": 72,
        "name": "Jule Game",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 307517,
        "dats": 1,
        "__1": ""
    },
    {
        "": 73,
        "name": "Lionside",
        "market": "Games",
        "status": "acquired",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 89506,
        "dats": 1,
        "__1": ""
    },
    {
        "": 75,
        "name": "Ismole",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 502415,
        "dats": 1,
        "__1": ""
    },
    {
        "": 76,
        "name": "KLab",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 883931,
        "dats": 1,
        "__1": ""
    },
    {
        "": 77,
        "name": "Mob Science",
        "market": "Games",
        "status": "acquired",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 834004,
        "dats": 1,
        "__1": ""
    },
    {
        "": 78,
        "name": "Kingnaru Entertainment",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 13636,
        "dats": 1,
        "__1": ""
    },
    {
        "": 80,
        "name": "Oberon Media",
        "market": "Games",
        "status": "acquired",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 710120,
        "dats": 1,
        "__1": ""
    },
    {
        "": 81,
        "name": "Openbucks",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 848311,
        "dats": 1,
        "__1": ""
    },
    {
        "": 82,
        "name": "Innovaspire",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 115616,
        "dats": 1,
        "__1": ""
    },
    {
        "": 84,
        "name": "MindFuse",
        "market": "Games",
        "status": "closed",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 375596,
        "dats": 1,
        "__1": ""
    },
    {
        "": 85,
        "name": "MeeVee",
        "market": "Games",
        "status": "acquired",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 583096,
        "dats": 1,
        "__1": ""
    },
    {
        "": 86,
        "name": "Mango Games",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 276580,
        "dats": 1,
        "__1": ""
    },
    {
        "": 88,
        "name": "Memetales",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 832546,
        "dats": 1,
        "__1": ""
    },
    {
        "": 89,
        "name": "LeBUZZ",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Baseball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "72,8",
        "Genres": "Sports",
        "Downloads": 895671,
        "dats": 1,
        "__1": ""
    },
    {
        "": 90,
        "name": "Mytopia",
        "market": "Games",
        "status": "acquired",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 881245,
        "dats": 1,
        "__1": ""
    },
    {
        "": 91,
        "name": "NutriVentures",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 206471,
        "dats": 1,
        "__1": ""
    },
    {
        "": 92,
        "name": "Karma Gaming",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 708163,
        "dats": 1,
        "__1": ""
    },
    {
        "": 93,
        "name": "JibJab",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 216461,
        "dats": 1,
        "__1": ""
    },
    {
        "": 95,
        "name": "Kngroo",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 503810,
        "dats": 1,
        "__1": ""
    },
    {
        "": 96,
        "name": "MinoMonsters",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 505760,
        "dats": 1,
        "__1": ""
    },
    {
        "": 97,
        "name": "Medio",
        "market": "Games",
        "status": "acquired",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 457472,
        "dats": 1,
        "__1": ""
    },
    {
        "": 99,
        "name": "MobbWorld Game Studios Philippines",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 273125,
        "dats": 1,
        "__1": ""
    },
    {
        "": 101,
        "name": "Loadcomplete",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 649932,
        "dats": 1,
        "__1": ""
    },
    {
        "": 104,
        "name": "Magic Tech Network",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 31248,
        "dats": 1,
        "__1": ""
    },
    {
        "": 105,
        "name": "Major League Gaming",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 800159,
        "dats": 1,
        "__1": ""
    },
    {
        "": 106,
        "name": "Pangalore",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 156200,
        "dats": 1,
        "__1": ""
    },
    {
        "": 107,
        "name": "Joyme.com",
        "market": "Mobile Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 773759,
        "dats": 1,
        "__1": ""
    },
    {
        "": 108,
        "name": "MXP4",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 613284,
        "dats": 1,
        "__1": ""
    },
    {
        "": 110,
        "name": "OnLive",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 824123,
        "dats": 1,
        "__1": ""
    },
    {
        "": 112,
        "name": "KIT digital",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 972779,
        "dats": 1,
        "__1": ""
    },
    {
        "": 113,
        "name": "Monstrous",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 466944,
        "dats": 1,
        "__1": ""
    },
    {
        "": 116,
        "name": "Opendisc",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 919248,
        "dats": 1,
        "__1": ""
    },
    {
        "": 118,
        "name": "Jinni",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 317310,
        "dats": 1,
        "__1": ""
    },
    {
        "": 120,
        "name": "Massively Fun",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 589663,
        "dats": 1,
        "__1": ""
    },
    {
        "": 121,
        "name": "LionWorks",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 219887,
        "dats": 1,
        "__1": ""
    },
    {
        "": 123,
        "name": "Mandy & Pandy",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 100435,
        "dats": 1,
        "__1": ""
    },
    {
        "": 124,
        "name": "JoyTunes",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 952000,
        "dats": 1,
        "__1": ""
    },
    {
        "": 125,
        "name": "Nostalgia Bingo",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 32170,
        "dats": 1,
        "__1": ""
    },
    {
        "": 126,
        "name": "KeyEffx",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 433213,
        "dats": 1,
        "__1": ""
    },
    {
        "": 129,
        "name": "Nukotoys",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 986714,
        "dats": 1,
        "__1": ""
    },
    {
        "": 130,
        "name": "Jenn Rykert",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 350036,
        "dats": 1,
        "__1": ""
    },
    {
        "": 131,
        "name": "OGPlanet",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 673876,
        "dats": 1,
        "__1": ""
    },
    {
        "": 132,
        "name": "Outplay Entertainment",
        "market": "Mobile Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 129911,
        "dats": 1,
        "__1": ""
    },
    {
        "": 133,
        "name": "Motion Math",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 268048,
        "dats": 1,
        "__1": ""
    },
    {
        "": 134,
        "name": "Joystickers",
        "market": "Mobile Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 214381,
        "dats": 1,
        "__1": ""
    },
    {
        "": 136,
        "name": "Motiga",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 950476,
        "dats": 1,
        "__1": ""
    },
    {
        "": 137,
        "name": "Miralupa",
        "market": "Mobile Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 365501,
        "dats": 1,
        "__1": ""
    },
    {
        "": 139,
        "name": "NetMovies",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 633551,
        "dats": 1,
        "__1": ""
    },
    {
        "": 140,
        "name": "lifeaction games",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 668035,
        "dats": 1,
        "__1": ""
    },
    {
        "": 141,
        "name": "KIXEYE",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 70364,
        "dats": 1,
        "__1": ""
    },
    {
        "": 142,
        "name": "MyPronostic",
        "market": "Games",
        "status": "closed",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 465996,
        "dats": 1,
        "__1": ""
    },
    {
        "": 143,
        "name": "LootWorks",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 571343,
        "dats": 1,
        "__1": ""
    },
    {
        "": 144,
        "name": "P4RC",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 179936,
        "dats": 1,
        "__1": ""
    },
    {
        "": 145,
        "name": "MyKontiki (ElÃ¤mysluotain Ltd)",
        "market": "Mobile Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 373962,
        "dats": 1,
        "__1": ""
    },
    {
        "": 146,
        "name": "PeerMe",
        "market": "Games",
        "status": "closed",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 778186,
        "dats": 1,
        "__1": ""
    },
    {
        "": 147,
        "name": "Koogame",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 152187,
        "dats": 1,
        "__1": ""
    },
    {
        "": 148,
        "name": "Mention Mobile",
        "market": "Mobile Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 370263,
        "dats": 1,
        "__1": ""
    },
    {
        "": 149,
        "name": "Outspark",
        "market": "Games",
        "status": "acquired",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 240322,
        "dats": 1,
        "__1": ""
    },
    {
        "": 152,
        "name": "Is That Odd",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 775626,
        "dats": 1,
        "__1": ""
    },
    {
        "": 153,
        "name": "Metaboli",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 775003,
        "dats": 1,
        "__1": ""
    },
    {
        "": 154,
        "name": "Lightning Gaming",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 277643,
        "dats": 1,
        "__1": ""
    },
    {
        "": 155,
        "name": "Lonely Sock",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 605168,
        "dats": 1,
        "__1": ""
    },
    {
        "": 156,
        "name": "MoSo",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 907250,
        "dats": 1,
        "__1": ""
    },
    {
        "": 157,
        "name": "MakeGamesWithUs",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 792124,
        "dats": 1,
        "__1": ""
    },
    {
        "": 158,
        "name": "Ohai",
        "market": "Games",
        "status": "closed",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 405407,
        "dats": 1,
        "__1": ""
    },
    {
        "": 160,
        "name": "NewAuto Video Technology",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 176006,
        "dats": 1,
        "__1": ""
    },
    {
        "": 161,
        "name": "Lucerotech LLC",
        "market": "Mobile Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 548097,
        "dats": 1,
        "__1": ""
    },
    {
        "": 162,
        "name": "kalidea",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 87244,
        "dats": 1,
        "__1": ""
    },
    {
        "": 165,
        "name": "InVisM",
        "market": "Games",
        "status": "closed",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 307697,
        "dats": 1,
        "__1": ""
    },
    {
        "": 166,
        "name": "iROKO Partners",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 374352,
        "dats": 1,
        "__1": ""
    },
    {
        "": 167,
        "name": "Metaplace",
        "market": "Games",
        "status": "acquired",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 51227,
        "dats": 1,
        "__1": ""
    },
    {
        "": 168,
        "name": "Next Games",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 999024,
        "dats": 1,
        "__1": ""
    },
    {
        "": 169,
        "name": "Koalah",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 195039,
        "dats": 1,
        "__1": ""
    },
    {
        "": 170,
        "name": "Jet Set Games",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 627714,
        "dats": 1,
        "__1": ""
    },
    {
        "": 171,
        "name": "Metacafe",
        "market": "Games",
        "status": "acquired",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 334722,
        "dats": 1,
        "__1": ""
    },
    {
        "": 172,
        "name": "Intelimax Media",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 330465,
        "dats": 1,
        "__1": ""
    },
    {
        "": 173,
        "name": "Party Earth",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 481826,
        "dats": 1,
        "__1": ""
    },
    {
        "": 174,
        "name": "OG-Vegas",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 467726,
        "dats": 1,
        "__1": ""
    },
    {
        "": 177,
        "name": "nWay",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 81988,
        "dats": 1,
        "__1": ""
    },
    {
        "": 178,
        "name": "Istpika",
        "market": "Games",
        "status": "acquired",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 375558,
        "dats": 1,
        "__1": ""
    },
    {
        "": 180,
        "name": "NextMusic.TV",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 342902,
        "dats": 1,
        "__1": ""
    },
    {
        "": 181,
        "name": "Live Youth Sports Network",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 42332,
        "dats": 1,
        "__1": ""
    },
    {
        "": 182,
        "name": "Linekong",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 356633,
        "dats": 1,
        "__1": ""
    },
    {
        "": 183,
        "name": "Monkey Puzzle Media",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 395227,
        "dats": 1,
        "__1": ""
    },
    {
        "": 186,
        "name": "Kentaura",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 572847,
        "dats": 1,
        "__1": ""
    },
    {
        "": 188,
        "name": "Krikle",
        "market": "Games",
        "status": "closed",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 966539,
        "dats": 1,
        "__1": ""
    },
    {
        "": 190,
        "name": "Iron Will Innovations",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 743978,
        "dats": 1,
        "__1": ""
    },
    {
        "": 191,
        "name": "Innobits",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 625405,
        "dats": 1,
        "__1": ""
    },
    {
        "": 192,
        "name": "Nival",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Basketball Sports",
        "Break-even Day": "27,28",
        "Retention Day-1": 69,
        "Retention Day-7": 56,
        "Retention Day-14": 50,
        "Retention Day-30": 42,
        "Success Rate": "79,4",
        "Genres": "Sports",
        "Downloads": 145459,
        "dats": 1,
        "__1": ""
    },
    {
        "": 193,
        "name": "EZ-Ticket",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 523609,
        "dats": 1,
        "__1": ""
    },
    {
        "": 194,
        "name": "Helpa",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 164822,
        "dats": 1,
        "__1": ""
    },
    {
        "": 196,
        "name": "FlexyMind",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 902519,
        "dats": 1,
        "__1": ""
    },
    {
        "": 197,
        "name": "Chill.com",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 844344,
        "dats": 1,
        "__1": ""
    },
    {
        "": 198,
        "name": "Funtactix",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 491065,
        "dats": 1,
        "__1": ""
    },
    {
        "": 199,
        "name": "Cause.it",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 517222,
        "dats": 1,
        "__1": ""
    },
    {
        "": 200,
        "name": "Gramble World BV",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 836803,
        "dats": 1,
        "__1": ""
    },
    {
        "": 201,
        "name": "Confetti Games",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 712216,
        "dats": 1,
        "__1": ""
    },
    {
        "": 202,
        "name": "7k7k.com",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 127549,
        "dats": 1,
        "__1": ""
    },
    {
        "": 204,
        "name": "Boomlagoon",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 631814,
        "dats": 1,
        "__1": ""
    },
    {
        "": 206,
        "name": "Flying Pig Digital",
        "market": "Games",
        "status": "closed",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 382924,
        "dats": 1,
        "__1": ""
    },
    {
        "": 207,
        "name": "Betable",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 388831,
        "dats": 1,
        "__1": ""
    },
    {
        "": 208,
        "name": "DraftDay",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 364477,
        "dats": 1,
        "__1": ""
    },
    {
        "": 209,
        "name": "Bloom Studio",
        "market": "Games",
        "status": "closed",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 695739,
        "dats": 1,
        "__1": ""
    },
    {
        "": 212,
        "name": "alife studios inc",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 149260,
        "dats": 1,
        "__1": ""
    },
    {
        "": 213,
        "name": "GridNetworks",
        "market": "Games",
        "status": "closed",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 649951,
        "dats": 1,
        "__1": ""
    },
    {
        "": 215,
        "name": "Gaikai",
        "market": "Games",
        "status": "acquired",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 291281,
        "dats": 1,
        "__1": ""
    },
    {
        "": 216,
        "name": "Critical Media",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 374795,
        "dats": 1,
        "__1": ""
    },
    {
        "": 218,
        "name": "Digital Chocolate",
        "market": "Mobile Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 408133,
        "dats": 1,
        "__1": ""
    },
    {
        "": 219,
        "name": "Box Score Games",
        "market": "Mobile Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 181920,
        "dats": 1,
        "__1": ""
    },
    {
        "": 220,
        "name": "Donya Labs",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 360861,
        "dats": 1,
        "__1": ""
    },
    {
        "": 221,
        "name": "Backflip Studios",
        "market": "Games",
        "status": "acquired",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 318130,
        "dats": 1,
        "__1": ""
    },
    {
        "": 222,
        "name": "CinemaKi",
        "market": "Games",
        "status": "closed",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 213966,
        "dats": 1,
        "__1": ""
    },
    {
        "": 224,
        "name": "Exavio",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 473263,
        "dats": 1,
        "__1": ""
    },
    {
        "": 226,
        "name": "FunGoPlay",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 709503,
        "dats": 1,
        "__1": ""
    },
    {
        "": 228,
        "name": "Breakout Studios",
        "market": "Mobile Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 644977,
        "dats": 1,
        "__1": ""
    },
    {
        "": 230,
        "name": "Charmcastle Entertainment Ltd.",
        "market": "Mobile Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 514537,
        "dats": 1,
        "__1": ""
    },
    {
        "": 231,
        "name": "Audio Network",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 577411,
        "dats": 1,
        "__1": ""
    },
    {
        "": 232,
        "name": "Gaia Interactive",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 56400,
        "dats": 1,
        "__1": ""
    },
    {
        "": 233,
        "name": "Infantium",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 445644,
        "dats": 1,
        "__1": ""
    },
    {
        "": 234,
        "name": "Halfbrick Studios",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 939746,
        "dats": 1,
        "__1": ""
    },
    {
        "": 235,
        "name": "Incuvo",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 459338,
        "dats": 1,
        "__1": ""
    },
    {
        "": 236,
        "name": "Altitude Games",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 941360,
        "dats": 1,
        "__1": ""
    },
    {
        "": 237,
        "name": "AMTT Digital Service Group",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 845495,
        "dats": 1,
        "__1": ""
    },
    {
        "": 238,
        "name": "Happy Elements",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 162246,
        "dats": 1,
        "__1": ""
    },
    {
        "": 240,
        "name": "GameWith",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 372638,
        "dats": 1,
        "__1": ""
    },
    {
        "": 241,
        "name": "Bangbite",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 416239,
        "dats": 1,
        "__1": ""
    },
    {
        "": 242,
        "name": "Art of the Dream",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Bold Action",
        "Break-even Day": "27,33",
        "Retention Day-1": 45,
        "Retention Day-7": 30,
        "Retention Day-14": 28,
        "Retention Day-30": 25,
        "Success Rate": "82,7",
        "Genres": "Action",
        "Downloads": 174040,
        "dats": 1,
        "__1": ""
    },
   
  
   
    {
        "": 1237,
        "name": "Ti Knight",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Table Strategy",
        "Break-even Day": "27,83",
        "Retention Day-1": 65,
        "Retention Day-7": 48,
        "Retention Day-14": 44,
        "Retention Day-30": 40,
        "Success Rate": "84,2",
        "Genres": "Strategy",
        "Downloads": 446585,
        "dats": 1,
        "__1": ""
    },
    {
        "": 1238,
        "name": "SuperMighty",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Table Strategy",
        "Break-even Day": "27,83",
        "Retention Day-1": 65,
        "Retention Day-7": 48,
        "Retention Day-14": 44,
        "Retention Day-30": 40,
        "Success Rate": "84,2",
        "Genres": "Strategy",
        "Downloads": 541361,
        "dats": 1,
        "__1": ""
    },
    {
        "": 1239,
        "name": "Tengaged",
        "market": "Games",
        "status": "operating",
        "Subgenres": "Table Strategy",
        "Break-even Day": "27,83",
        "Retention Day-1": 65,
        "Retention Day-7": 48,
        "Retention Day-14": 44,
        "Retention Day-30": 40,
        "Success Rate": "84,2",
        "Genres": "Strategy",
        "Downloads": 91214,
        "dats": 1,
        "__1": ""
    }
  ]
  let breakEvenPoint = 33 - 27 //break even day 30  * 10 * slidervalue 
  let retentionRateValue = 12 //retday-30 * rrvalue
  let successRateValue =  10 //successrate * ss 
  
  
   
   


  const parse = (val) => val.replace(/^\$/, "");

  const [showResult, setResult] = React.useState(false);

  const [sliderValue, setSliderValue] = React.useState(50);
  const [rrValue, setRrValue] = React.useState(50);
  const [ssValue, setSsValue] = React.useState(50);

  const [score, setScore] = React.useState(0);

  const [genre, setGenre] = React.useState("exampleGenre");
 
  const [maxscoreGame, maxScore] = React.useState(1);
  
  const predict = async  () => {
   
    

    estData.map(game => {
      setScore(((parseFloat( game["Break-even Day"].replace(",",".")) - 33) * (-10) * sliderValue) + (game["Retention Day-30"] * rrValue) + (parseFloat(game["Success Rate"].replace(",",".")) * ssValue));
        if(score > maxscoreGame) maxScore(score)
     })

     console.log(score)

     estData.map(game => {
      setScore(((parseFloat(game["Break-even Day"].replace(",",".")) - 33) * (-10) * sliderValue) + (game["Retention Day-30"] * rrValue) + (parseFloat(game["Success Rate"].replace(",",".") )* ssValue));
      if(score == maxscoreGame) setGenre(game["Subgenres"])
     })
  }
 

  const labelStyles = {
    mt: "2",
    ml: "-2.5",
    fontSize: "sm",
  };

  const handleResult = () => {
    predict();
    if (!showResult) setResult(true);
    else setResult(false);
    console.log("okey");
  };

  return (
    <Box>
      <Container>
        <Text fontSize='3xl' mt={100}>Choose Importance of Those...</Text>
        <Box height={50} />
        <FormControl id="email">
          <Box pt={4} pb={2}>
            <FormLabel mb={10}>Break-Even Point</FormLabel>
            <Slider
              aria-label="slider-ex-6"
              onChange={(val) => setSliderValue(val)}
            >
              <SliderMark value={25} {...labelStyles}>
                25%
              </SliderMark>
              <SliderMark value={50} {...labelStyles}>
                50%
              </SliderMark>
              <SliderMark value={75} {...labelStyles}>
                75%
              </SliderMark>
              <SliderMark
                value={sliderValue}
                textAlign="center"
                bg="blue.500"
                color="white"
                mt="-10"
                ml="-5"
                w="12"
              >
                {sliderValue}%
              </SliderMark>
              <SliderTrack>
                <SliderFilledTrack />
              </SliderTrack>
              <SliderThumb />
            </Slider>
          </Box>
          <Box pt={6} pb={2}>
            <FormLabel mb={10}>Retention Rate</FormLabel>
            <Slider
              aria-label="slider-ex-6"
              onChange={(val) => setRrValue(val)}
            >
              <SliderMark value={25} {...labelStyles}>
                25%
              </SliderMark>
              <SliderMark value={50} {...labelStyles}>
                50%
              </SliderMark>
              <SliderMark value={75} {...labelStyles}>
                75%
              </SliderMark>
              <SliderMark
                value={rrValue}
                textAlign="center"
                bg="blue.500"
                color="white"
                mt="-10"
                ml="-5"
                w="12"
              >
                {rrValue}%
              </SliderMark>
              <SliderTrack>
                <SliderFilledTrack />
              </SliderTrack>
              <SliderThumb />
            </Slider>
          </Box>
          <Box pt={6} pb={2}>
            <FormLabel mb={10}>Success Rate</FormLabel>
            <Slider
              aria-label="slider-ex-6"
              onChange={(val) => setSsValue(val)}
            >
              <SliderMark value={25} {...labelStyles}>
                25%
              </SliderMark>
              <SliderMark value={50} {...labelStyles}>
                50%
              </SliderMark>
              <SliderMark value={75} {...labelStyles}>
                75%
              </SliderMark>
              <SliderMark
                value={ssValue}
                textAlign="center"
                bg="blue.500"
                color="white"
                mt="-10"
                ml="-5"
                w="12"
              >
                {ssValue}%
              </SliderMark>
              <SliderTrack>
                <SliderFilledTrack />
              </SliderTrack>
              <SliderThumb />
            </Slider>
          </Box>
          <Flex justifyContent={"center"}>
          <Button
          
          onClick={handleResult}
          mb={5}
          mt={50}
          colorScheme="blue"
          variant="solid"
        >
          Make Prediction
        </Button>
          </Flex>
          
        </FormControl>
      </Container>
      {showResult && (
        <Flex justifyContent={"center"}>
        <Text fontSize='3xl' >Your best choice: {genre}</Text>

        </Flex>
      )}
    </Box>
  );
}
